version: '3'
services:
  node:
    image: node:10
    command: npm run start
    volumes:
      - "./src:/src"
    working_dir: "/src"
    ports:
      - "8080:8080"
    environment:
      PORT: 8080

  docker:
    image: docker:latest
    volumes:
      - "./src:/src"
    working_dir: "/src"

