# Usage: HOME=$HOME docker-compose up
version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm run watch
    volumes:
      - "./src:/src"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/volumes:/volumes"
    working_dir: "/src"
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      HOME: "${HOME}"
