version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile.node
    command: npm run start
    volumes:
      - "./src:/src"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/volumes:/volumes"
      # curl -H 'Content-Type: application/json' --unix-socket /var/run/docker.sock localhost:4243/containers/zabbix-agent/exec -d '{"Cmd":["date"]}'
    working_dir: "/src"
    ports:
      - "8080:8080"
    environment:
      PORT: 8080

  data_volume_host:
    container_name: data_volume_host
    image: debian:latest
    volumes:
      - "~/volumes:/volumes"
    working_dir: "/volumes"
